/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Amigo;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gustav
 */
public class GerenciaAmigo extends javax.swing.JFrame {

        private Amigo objAmigo;
    /**
     * Creates new form GerenciaAmigo
     */
    public GerenciaAmigo() {
        initComponents();
        this.objAmigo = new Amigo();
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaGerenciaA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoTelefoneGerenciaA = new javax.swing.JTextField();
        CampoNomeGerenciaA = new javax.swing.JTextField();
        BtCancelarGerenciaA = new javax.swing.JButton();
        BtAlterarGerenciaA = new javax.swing.JButton();
        BtApagarGerenciaA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaGerenciaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaGerenciaA.setShowGrid(false);
        TabelaGerenciaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaGerenciaAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaGerenciaA);

        jLabel1.setText("Nome");

        jLabel2.setText("Telefone");

        CampoTelefoneGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneGerenciaAActionPerformed(evt);
            }
        });

        CampoNomeGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeGerenciaAActionPerformed(evt);
            }
        });

        BtCancelarGerenciaA.setText("Cancelar");
        BtCancelarGerenciaA.setToolTipText("");
        BtCancelarGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarGerenciaAActionPerformed(evt);
            }
        });

        BtAlterarGerenciaA.setText("Alterar");
        BtAlterarGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarGerenciaAActionPerformed(evt);
            }
        });

        BtApagarGerenciaA.setText("Apagar");
        BtApagarGerenciaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtApagarGerenciaAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoNomeGerenciaA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoTelefoneGerenciaA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BtCancelarGerenciaA)
                        .addGap(30, 30, 30)
                        .addComponent(BtAlterarGerenciaA)
                        .addGap(30, 30, 30)
                        .addComponent(BtApagarGerenciaA)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoNomeGerenciaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CampoTelefoneGerenciaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCancelarGerenciaA)
                    .addComponent(BtAlterarGerenciaA)
                    .addComponent(BtApagarGerenciaA))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaGerenciaAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaGerenciaAMouseClicked
        // TODO add your handling code here:
        if (this.TabelaGerenciaA.getSelectedRow() != -1) {

            String nome = this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 1).toString();
            String telefone = this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 2).toString();

            this.CampoNomeGerenciaA.setText(nome);
            this.CampoTelefoneGerenciaA.setText(telefone);



        }                                     
    }//GEN-LAST:event_TabelaGerenciaAMouseClicked

    private void CampoTelefoneGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneGerenciaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneGerenciaAActionPerformed

    private void BtCancelarGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarGerenciaAActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtCancelarGerenciaAActionPerformed

    private void BtAlterarGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarGerenciaAActionPerformed
        // TODO add your handling code here:
        try {
            // recebendo e validando dados da interface gr�fica.
            int id = 0;
            String nome = "";
            String telefone = "";

            if (this.CampoNomeGerenciaA.getText().length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.CampoNomeGerenciaA.getText();
            }

            if (this.CampoTelefoneGerenciaA.getText().length() != 11) {
                throw new Mensagens("Numero deve ter ddd.");
            } else {
                telefone = this.CampoTelefoneGerenciaA.getText();
            }

            if (this.TabelaGerenciaA.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Aluno para Alterar");
            } else {
                id = Integer.parseInt(this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 0).toString());
            }

            // envia os dados para o Aluno processar
            if (this.objAmigo.UpdateAmigoBD(nome,telefone,id)) {

                // limpa os campos
                this.CampoNomeGerenciaA.setText("");
                this.CampoTelefoneGerenciaA.setText("");
                JOptionPane.showMessageDialog(rootPane, "Amigo Alterado com Sucesso!");

            }
            System.out.println(this.objAmigo.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um n�mero.");
        } finally {
            carregaTabela(); // atualiza a tabela.
        }
   
    }//GEN-LAST:event_BtAlterarGerenciaAActionPerformed

    private void CampoNomeGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeGerenciaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeGerenciaAActionPerformed

    private void BtApagarGerenciaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtApagarGerenciaAActionPerformed
        // TODO add your handling code here:
        
         try {
            // validando dados da interface gr�fica.
            int id = 0;
            if (this.TabelaGerenciaA.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Amigo para APAGAR");
            } else {
                id = Integer.parseInt(this.TabelaGerenciaA.getValueAt(this.TabelaGerenciaA.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Amigo ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Aluno processar
                if (this.objAmigo.DeleteAmigoBD(id)) {

                    // limpa os campos
                    this.CampoNomeGerenciaA.setText("");
                    this.CampoTelefoneGerenciaA.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Amigo Apagado com Sucesso!");

                }
            }
            System.out.println(this.objAmigo.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_BtApagarGerenciaAActionPerformed

    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.TabelaGerenciaA.getModel();
        modelo.setNumRows(0);

        ArrayList<Amigo> minhalista = new ArrayList<>();
        minhalista = objAmigo.getMinhaLista();

        for (Amigo a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getTelefone(),

            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterarGerenciaA;
    private javax.swing.JButton BtApagarGerenciaA;
    private javax.swing.JButton BtCancelarGerenciaA;
    private javax.swing.JTextField CampoNomeGerenciaA;
    private javax.swing.JTextField CampoTelefoneGerenciaA;
    private javax.swing.JTable TabelaGerenciaA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
